### ISSUE TITLE
General "look up" class for histogram that opens before looping accessed while looping

### ISSUE THREAD

**Issue by lcorcodilos** [lcorcodilos/TIMBER#2]
The idea is to make a constructor that opens up the histogram and then a member function of the class (eval) that takes as input a branch name to evaluate and find the corresponding bin and bin value in the already opened histogram

We can also start simple and then try adding extra features (like assume that the histogram will always be 1D and once that's working, we can try adding functionality to check for 2D or 3D histograms so those can be used automatically as well)

**Comment by lcorcodilos** [comment]
Becky's first shot.

`#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <cstring>
#include <string>
#include "TROOT.h"
#include "TSystem.h"
#include "TTree.h"
#include "TFile.h"
#include "TH1F.h"
#include "TH2F.h"
using namespace std;
class BinHistoFunc2 {
public:
  //  BinHistoFunc(){} // Constructor without arguments
    float histoFunc(std::string histtype, std::string filename, std::string histname){ //histogram function that takes two file arguments
        TFile *F = TFile::Open(filename.c_str());
        float val;
        if (histtype=="1D"){
            TH1F *hist = (TH1F *)F->Get(histname.c_str());
            int binsx = hist->GetNbinsX();
            std::cout << "hi" << std::endl;
        //  std::cout << F << std::endl;
            std::cout << binsx << std::endl;
            for(int b = 1; b < binsx; b++){
              float val = hist->GetBinContent(b);
              std::cout << "val is " << val << std::endl;
              std::cout << "bin is " << b << std::endl;
            };
        }
        else if (histtype=="2D"){
            TH2F *hist = (TH2F *)F->Get(histname.c_str());
            int binsx = hist->GetNbinsX();
            int binsy = hist->GetNbinsY();
        //  std::cout << "hi" << std::endl;
        //  std::cout << F << std::endl;
        //      std::cout << binsx << std::endl;
            for(int bx = 1; bx < binsx; bx++){
                for(int by = 1; by < binsy; by++){
                    float val = hist->GetBinContent(bx, by);
                    std::cout << "val is " << val << std::endl;
                    // std::cout << "bin is " << b << std::endl;
                };
            };
        } 
         return val;  
    }
};
BinHistoFunc2 obj;
float a = obj.histoFunc("2D", "example.root", "MtwvMtPass");`

**Comment by lcorcodilos** [comment]
There are some other tricks we can do though to make it even better

Like we can ask the type of the histogram passed in the argument to see if it inherits from TH1, TH2, or TH3 to get the dimensionality (and then you don't need it as an argument)

I'll make like a to-do list.

**Comment by lcorcodilos** [comment]
- [ ] Determine type from object passed in argument. There's something called `dynamic_cast` which can change an objects type to a type from which it inherits but returns NULL if it won't work. So like `dynamic_cast<const TH2*>(hist)`
would return NULL if hist isn't `TH2I`, `TH2F`, etc because those all inherit from the base class `TH2`. We have to be careful though because all histograms in ROOT (no matter the dimension) inherit from `TH1` so any if statement should check first if the histogram can be cast to `TH3` or `TH2` and then do `TH1`s as the `else` at the end.
- [ ] Setup the constructor to take the file and histogram names as input. Constructor will just load the histogram
- [ ] Setup `histoFunc` to return the bin contents of the loaded histogram. May be more appropriate to rename `histoFunc` to `GetBinContent`

**Comment by rek81** [comment]
Version with dynamic cast
[BinHistoFunc_New.txt](https://github.com/lcorcodilos/HAMMER/files/4846980/BinHistoFunc_New.txt)

**Comment by lcorcodilos** [comment]
This looks great! The only thing is that I don't think I was clear about was the desired output from the functions. What you've written is actually doing more than what's needed. We just need to return a specific requested bin value (by bin number or axis value) and we don't need to loop over all bins. I'll try to explain by example. This is the beginning of your GetBinContents() function (dropping the std::cout)
```
float GetBinContents(void){ 
    float val;
    if (hist1 != 0) {
      int binsx = hist1->GetNbinsX();
      for(int b = 1; b < binsx; b++){
        val = hist1->GetBinContent(b);
      }
    }
    ...
   return val;
```

This can be simplified to this (note I also changed the function arguments):
```
float GetBinContents(int xbin, int ybin = 0, int zbin = 0){ 
    float val;
    if (hist1 != 0) {
      val = hist1->GetBinContent(xbin);
    }
   ...
   return val;
```

Let me know if that makes sense and feel free to send questions, obviously. But next step is to have GetBinContents and and GetBinContentsByAxis to just be the specific bin lookup. Then I think we can drop it in to the repo!

**Comment by lcorcodilos** [comment]
Added in PR #19
