### ISSUE TITLE
Need a example for short run

### ISSUE THREAD

**Issue by shu-xiao** [lcorcodilos/TIMBER#4]
I found a code of short run here. [code](https://github.com/dmajumder/X_YH_4b/blob/bb9961830bdcefe922cb9ff8969c73c5fd34633a/eventSelection.py#L56-L58)
It use Range function to limit the range but it's used after you call EnableImplicitMT.
So maybe we need a example to tell user not to use EnableImplicitMT or move it down if Range is used.

**Comment by lcorcodilos** [comment]
Added a dedicated `Range()` method so that the three linked lines can be replaced by one simple one. Warned of the `ROOT.EnableImplicitMT()` issue in the docs for the `Range()` method. Added an example (with the `ROOT.EnableImplicitMT()` issue explained) to examples/ex1.py.
